### ISSUE TITLE
 The Things Node button release does not provide time pressed 

### ISSUE THREAD

**Issue by pe1mew** [TheThingsNetwork/arduino-node-lib#9]
The function onButtonRelease() is not delivering the time the button is pressed. 
it is always 0.

**Comment by johanstokking** [comment]
Thanks for reporting. I'm not seeing any obvious errors in the code. You do get the button press callback, right?

Is this behavior consistent?

**Comment by pe1mew** [comment]
No, I do not get the button press call back, but: after i pressed the button I do get the button release call back. when I release I get no call back

**Comment by hallard** [comment]
@johanstokking IRQ management on this type of devices are sometimes tricky, anyway I think I fixed the issue while trying low power mode

- First do not sleep while the button is pressed (this may stop the ms timer) and return wrong values of duration
- IRQ are fired quickly, and since there is no debounce on button, we need to check that main loop has seen (ACK) the press detected before seeing and doing any release job.
- also it's best to declare any var used in IRQ as volatile to avoid race condition

Just let me know if it just works

**Comment by hallard** [comment]
Should also be fixed in #15
